name: 'lightdash_demo_training'
config-version: 2
profile: 'lightdash-demo-training'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  lightdash_demo_training:
    +materialized: table

seeds:
  lightdash_demo_training:
    +column_types:
      created_at: timestamp
      first_logged_in_at: timestamp
      latest_logged_in_at: timestamp
      event_timestamp: timestamp
      created_date: timestamp
