chartConfig:
  config:
    comparisonFormat: percentage
    comparisonLabel: Compared to 2024
    flipColors: false
    label: Total Revenue 2025
    selectedField: deals_total_amount
    showBigNumberLabel: false
    showComparison: true
  type: big_number
contentType: chart
dashboardSlug: sales-overview-wip
description: Sum of revenue in Q3 for 2024 and 2025
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - deals_created_date_year
  exploreName: deals
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - deals_total_amount
  sorts:
    - descending: true
      fieldId: deals_created_date_year
  tableCalculations: []
name: Q3 Revenue YoY
slug: 2025-revenue
spaceSlug: shared/demo-space/sales-marketing
tableConfig:
  columnOrder:
    - deals_created_date_year
    - deals_total_amount
tableName: deals
verification: null
version: 1
