chartConfig:
  config:
    groupColorOverrides:
      Enterprise: "#feed01"
      Midmarket: "#FFC54D"
      SMB: "#FFEFCC"
    groupFieldIds:
      - accounts_segment
    groupLabelOverrides: {}
    groupSortOverrides:
      - Enterprise
      - Midmarket
      - SMB
    groupValueOptionOverrides: {}
    isDonut: true
    legendMaxItemLength: 30
    legendPosition: horizontal
    metricId: tracks_event_count
    showLegend: true
    showPercentage: true
    showValue: false
    valueLabel: inside
  type: pie
contentType: chart
dashboardSlug: wip-product-analytics
description: ""
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensions:
    - accounts_segment
  exploreName: tracks
  filters:
    dimensions:
      and:
        - id: b14a6c24-3f56-49f3-9f77-e07ba3e8f8ce
          operator: inThePast
          required: true
          settings:
            unitOfTime: months
          target:
            fieldId: tracks_timestamp
          values:
            - 12
        - id: 034963f2-5065-40e6-88f0-051bbe433b75
          operator: equals
          required: false
          target:
            fieldId: tracks_name
          values:
            - api_call_made
      id: 8b309c17-eeb3-4bf6-b7df-3377221b6c11
  limit: 500
  metricOverrides: {}
  metrics:
    - tracks_event_count
    - tracks_unique_user_count
  sorts:
    - descending: true
      fieldId: tracks_event_count
  tableCalculations:
    - displayName: Avg. Events per User
      format:
        separator: default
        type: default
      name: avg_events_per_user
      sql: Round(${tracks.event_count} / ${tracks.unique_user_count}, 2)
      type: number
  timezone: project_timezone
name: API Call Engagement
slug: api-call-engagement-by-segment
spaceSlug: executive-reporting-git-owned
tableConfig:
  columnOrder:
    - accounts_segment
    - tracks_event_count
    - tracks_unique_user_count
    - avg_events_per_user
tableName: tracks
verification: null
version: 1
