chartKind: vertical_bar
config:
  display:
    series:
      avg_days_in_sales_cycle_avg:
        color: "#BFAAF9"
        valueLabelPosition: top
    xAxis:
      label: Deal Created Month
    yAxis:
      - label: Avg. Days in Sales Cycle
      - {}
  fieldConfig:
    x:
      reference: deals_created_month
      type: category
    "y":
      - aggregation: avg
        reference: avg_days_in_sales_cycle
  metadata:
    version: 1
  type: vertical_bar
contentType: sql_chart
description: >-
  The average amount of time deals spent from open to close in the sales cycle
  (regardless of win/lose)
limit: 500
name: Avg. Days in Sales Cycle
slug: avg-days-in-sales-cycle
spaceSlug: shared
sql: |
  WITH metrics AS (
    SELECT
      DATE_TRUNC(deals.created_date, MONTH) AS deals_created_date_month,
      DATE_TRUNC(deals.created_date, DAY) AS deals_created_date_day,
      CASE
        WHEN EXTRACT(MONTH FROM deals.created_date) = 6 THEN DATE_ADD(deals.created_date, INTERVAL 30 DAY)
        WHEN EXTRACT(MONTH FROM deals.created_date) = 7 THEN DATE_ADD(deals.created_date, INTERVAL 25 DAY)
        WHEN EXTRACT(MONTH FROM deals.created_date) = 8 THEN DATE_ADD(deals.created_date, INTERVAL 20 DAY)
        WHEN EXTRACT(MONTH FROM deals.created_date) = 9 THEN DATE_ADD(deals.created_date, INTERVAL 15 DAY)
        ELSE deals.created_date
      END AS closed_date
    FROM `lightdash-healthcare-demo`.`lightdash_demo_saas`.`deals` AS deals
    WHERE deals.stage IN ('Closed Won', 'Lost', 'Won')
  )

  SELECT
    FORMAT_DATE('%Y-%m', deals_created_date_month) AS deals_created_month,
    ROUND(AVG(DATE_DIFF(closed_date, deals_created_date_day, DAY)), 1) AS avg_days_in_sales_cycle
  FROM metrics
  WHERE deals_created_date_month > "2025-05-01"
  GROUP BY deals_created_month
  ORDER BY deals_created_month DESC
  LIMIT 500;
version: 1
