chartConfig:
  config:
    eChartsConfig:
      legend:
        show: false
      series:
        - color: "#8001FE"
          encode:
            xRef:
              field: accounts_segment
            yRef:
              field: tracks_event_count
          isFilteredOut: false
          label:
            position: top
            show: true
          type: bar
          yAxisIndex: 0
      tooltip: ""
      xAxis:
        - name: Segment
          sortType: default
      yAxis:
        - name: Logins
    layout:
      flipAxes: false
      xField: accounts_segment
      yField:
        - tracks_event_count
  type: cartesian
contentType: chart
dashboardSlug: wip-product-analytics
description: How many successful logins come from each customer segment?
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensions:
    - accounts_segment
  exploreName: tracks
  filters:
    dimensions:
      and:
        - id: b14a6c24-3f56-49f3-9f77-e07ba3e8f8ce
          operator: inThePast
          required: true
          settings:
            unitOfTime: months
          target:
            fieldId: tracks_timestamp
          values:
            - 12
        - id: 034963f2-5065-40e6-88f0-051bbe433b75
          operator: equals
          required: false
          target:
            fieldId: tracks_name
          values:
            - login_successful
      id: a79eba3b-6f5b-430f-9fc8-6625364ced9d
  limit: 500
  metricOverrides: {}
  metrics:
    - tracks_event_count
    - tracks_unique_user_count
  sorts:
    - descending: true
      fieldId: tracks_event_count
  tableCalculations:
    - displayName: Avg. Events per User
      format:
        separator: default
        type: default
      name: avg_events_per_user
      sql: Round(${tracks.event_count} / ${tracks.unique_user_count}, 2)
      type: number
  timezone: project_timezone
name: Login Engagement
slug: login-engagement-by-segment
spaceSlug: executive-reporting-git-owned
tableConfig:
  columnOrder:
    - accounts_segment
    - tracks_event_count
    - tracks_unique_user_count
    - avg_events_per_user
tableName: tracks
verification: null
version: 1
