chartConfig:
  config:
    conditionalFormattings: []
    eChartsConfig:
      legend:
        orient: horizontal
        show: true
        type: plain
      series:
        - color: "#D1CCFF"
          encode:
            xRef:
              field: deals_created_date_month
            yRef:
              field: cumulative_deal_amount
          isFilteredOut: false
          label:
            position: top
            show: true
          type: bar
          yAxisIndex: 1
        - color: "#8001FE"
          encode:
            xRef:
              field: deals_created_date_month
            yRef:
              field: deals_unique_deals
          isFilteredOut: false
          label:
            position: top
            show: true
          type: line
          yAxisIndex: 0
      showAxisTicks: false
      tooltip: ""
      xAxis:
        - name: Month
          rotate: 45
      yAxis:
        - name: Deals
        - name: Cumulative Deal Amount ($)
    layout:
      flipAxes: false
      showGridX: false
      showGridY: true
      xField: deals_created_date_month
      yField:
        - deals_unique_deals
        - cumulative_deal_amount
  type: cartesian
contentType: chart
dashboardSlug: sales-overview-wip
description: ""
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - deals_created_date_month
  exploreName: deals
  filters:
    dimensions:
      and:
        - id: d3e8abf0-9aba-45e7-8284-655c35c54624
          operator: equals
          required: false
          target:
            fieldId: deals_stage
          values:
            - Won
      id: 0c0bf5cd-b707-4b08-ab87-48d52502da53
    metrics:
      and: []
      id: e95fa0f8-73f1-47bc-9979-aa880165216f
    tableCalculations:
      and: []
      id: e83421c0-a80d-4fb4-afd9-c7fc0451b04d
  limit: 500
  metricOverrides: {}
  metrics:
    - deals_unique_deals
    - deals_total_amount
  sorts:
    - descending: false
      fieldId: deals_created_date_month
  tableCalculations:
    - displayName: Cumulative deal amount
      format:
        compact: thousands
        currency: USD
        round: 0
        separator: default
        type: currency
      name: cumulative_deal_amount
      sql: |-
        sum(${deals.total_amount}) over (
            ORDER BY ${deals.created_date_month}
            RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)
      type: number
name: Monthly Won Deals and Cumulative Deal Value
slug: monthly-won-deals-and-cumulative-deal-value
spaceSlug: shared/demo-space/sales-marketing
tableConfig:
  columnOrder:
    - deals_created_date_month
    - deals_unique_deals
    - deals_total_amount
    - cumulative_deal_amount
tableName: deals
verification: null
version: 1
