chartConfig:
  config:
    comparisonFormat: percentage
    comparisonLabel: vs. Previous Month
    flipColors: false
    label: Open Deal Value
    selectedField: deals_total_amount
    showBigNumberLabel: true
    showComparison: true
  type: big_number
contentType: chart
dashboardSlug: sales-overview-wip
description: Current pipeline value
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - deals_created_date_month
  exploreName: deals
  filters:
    dimensions:
      and:
        - id: cf43bc99-6f61-42fc-bb8b-d14766fef1ce
          operator: equals
          required: false
          target:
            fieldId: deals_stage
          values:
            - Negotiation
            - New
            - PoC
            - Proposal
            - Qualified
      id: 179ef95a-6531-4d1e-a337-ca0091bc7be6
  limit: 2
  metricOverrides: {}
  metrics:
    - deals_total_amount
  sorts:
    - descending: true
      fieldId: deals_created_date_month
  tableCalculations: []
name: Pipeline Value
slug: pipeline-value
spaceSlug: shared/demo-space/sales-marketing
tableConfig:
  columnOrder:
    - deals_created_date_month
    - deals_total_amount
tableName: deals
verification: null
version: 1
