chartConfig:
  config:
    colorOverrides:
      Closed Won: "#E9E5F9"
      Negotiation: "#BFAAF9"
      New: "#D8CFF7"
      PoC: "#9B84F3"
      Qualified: "#6B4DE6"
    dataInput: column
    fieldId: deals_unique_deals
    labelOverrides:
      Negotiation: Negotiation
      New: PoC
      PoC: Qualified
      Qualified: New
    labels:
      position: right
      showPercentage: true
      showValue: true
    legendPosition: vertical
    showLegend: true
  type: funnel
contentType: chart
dashboardSlug: sales-overview-wip
description: ""
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - deals_stage
    - deals_stage_order
  exploreName: deals
  filters:
    dimensions:
      and:
        - id: be53b79b-9238-4866-abd9-5b891ddb14a3
          operator: equals
          required: false
          target:
            fieldId: deals_created_date_month
          values:
            - 2025-05
        - id: d9a50e14-490e-412e-90b0-d61d648a1420
          operator: notEquals
          required: false
          target:
            fieldId: deals_stage
          values:
            - Lost
            - Won
      id: 617dabb7-4f48-4580-85e3-9fcf336f73f7
  limit: 500
  metricOverrides: {}
  metrics:
    - deals_unique_deals
  sorts:
    - descending: true
      fieldId: deals_stage_order
      nullsFirst: true
  tableCalculations: []
name: Sales Funnel
slug: sales-funnel
spaceSlug: shared/demo-space/sales-marketing
tableConfig:
  columnOrder:
    - deals_stage
    - deals_stage_order
    - deals_unique_deals
tableName: deals
verification: null
version: 1
