chartConfig:
  config:
    eChartsConfig:
      legend:
        show: false
      series:
        - color: "#BFAAF9"
          encode:
            xRef:
              field: accounts_industry
            yRef:
              field: deals_average_amount
          isFilteredOut: false
          label:
            position: top
            show: true
          type: bar
          yAxisIndex: 0
      tooltip: "Total Deal Value: ${deals_total_amount}"
    layout:
      xField: accounts_industry
      yField:
        - deals_average_amount
  type: cartesian
contentType: chart
dashboardSlug: sales-overview-wip
description: ""
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - accounts_industry
  exploreName: accounts
  filters:
    dimensions:
      and:
        - id: 7d827f3b-54bb-4f53-a439-e6426c7f97a8
          operator: equals
          required: false
          target:
            fieldId: deals_stage
          values:
            - Won
        - id: 05c3a43f-eb7c-4831-a71a-5443c3c0f236
          operator: equals
          required: false
          target:
            fieldId: accounts_segment
          values:
            - Enterprise
            - Midmarket
            - SMB
      id: f99a862d-fd0a-4a65-8307-81eeb6de2481
  limit: 10
  metricOverrides:
    deals_average_amount:
      formatOptions:
        compact: thousands
        currency: USD
        round: 0
        separator: default
        type: currency
  metrics:
    - deals_average_amount
    - deals_total_amount
  sorts:
    - descending: true
      fieldId: deals_average_amount
  tableCalculations: []
name: Top 10 Industries by Avg. Won Deal Value
slug: top-10-industries-by-avg-won-deal-value
spaceSlug: shared/demo-space/sales-marketing
tableConfig:
  columnOrder:
    - accounts_industry
    - deals_average_amount
    - deals_total_amount
tableName: accounts
verification: null
version: 1
