chartConfig:
  config:
    eChartsConfig:
      legend:
        show: false
      series:
        - color: "#8001FE"
          encode:
            xRef:
              field: accounts_segment
            yRef:
              field: tracks_unique_user_count
          isFilteredOut: false
          label:
            position: top
            show: true
          type: bar
          yAxisIndex: 0
      tooltip: ""
      xAxis:
        - name: Segment
          sortType: default
      yAxis:
        - name: Unique Users
    layout:
      flipAxes: false
      xField: accounts_segment
      yField:
        - tracks_unique_user_count
  type: cartesian
contentType: chart
dashboardSlug: wip-product-analytics
description: ""
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensions:
    - accounts_segment
  exploreName: tracks
  filters:
    dimensions:
      and:
        - id: cb256b2d-b923-400c-9b14-6c974fb7ea34
          operator: equals
          target:
            fieldId: tracks_name
          values:
            - workspace_created
      id: workspace-filter
  limit: 10
  metricOverrides: {}
  metrics:
    - tracks_unique_user_count
  sorts:
    - descending: true
      fieldId: tracks_unique_user_count
  tableCalculations: []
  timezone: project_timezone
name: Workspace Created by Segment
slug: workspace-created-by-segment
spaceSlug: executive-reporting-git-owned
tableConfig:
  columnOrder:
    - accounts_segment
    - tracks_unique_user_count
tableName: tracks
verification: null
version: 1
