chartConfig:
  config:
    eChartsConfig:
      grid:
        bottom: 30px
        containLabel: true
        left: 26px
        right: 25px
        top: 70px
      legend:
        type: plain
      series:
        - color: "#8001FE"
          encode:
            xRef:
              field: deals_created_date_month_name
            yRef:
              field: deals_total_amount
              pivotValues:
                - field: deals_created_date_year
                  value: "2025-01-01T00:00:00Z"
          isFilteredOut: false
          label:
            position: top
            show: true
          markLine:
            data:
              - label:
                  formatter: Revenue Goal
                  position: start
                lineStyle:
                  color: "#FFC54D"
                name: Revenue Goal
                uuid: 68fb613a-4deb-4b3a-9084-6b03e5cc7bfb
                yAxis: "100000"
            lineStyle:
              color: "#000"
              type: solid
              width: 3
            symbol: none
          showSymbol: true
          smooth: false
          type: line
          yAxisIndex: 0
        - color: "#D9B3FF"
          encode:
            xRef:
              field: deals_created_date_month_name
            yRef:
              field: deals_total_amount
              pivotValues:
                - field: deals_created_date_year
                  value: "2024-01-01T00:00:00Z"
          isFilteredOut: false
          label:
            position: top
            show: true
          showSymbol: true
          smooth: false
          type: line
          yAxisIndex: 0
        - color: "#D1CCFF"
          encode:
            xRef:
              field: deals_created_date_month_name
            yRef:
              field: deals_total_amount
              pivotValues:
                - field: deals_created_date_year
                  value: "2023-01-01T00:00:00Z"
          isFilteredOut: false
          label:
            position: top
            show: true
          showSymbol: true
          smooth: false
          type: line
          yAxisIndex: 0
      tooltip: ""
      xAxis:
        - inverse: false
          name: Month
          sortType: default
      yAxis:
        - max: "150000"
          min: "0"
          name: ""
        - name: ""
    layout:
      flipAxes: false
      xField: deals_created_date_month_name
      yField:
        - deals_total_amount
    metadata:
      deals_total_amount.2023-01-01T00:00:00Z:
        color: "#D1CCFF"
      deals_total_amount.2024-01-01T00:00:00Z:
        color: "#D9B3FF"
      deals_total_amount.2025-01-01T00:00:00Z:
        color: "#8001FE"
  type: cartesian
contentType: chart
dashboardSlug: sales-overview-wip
description: What was the total deal amount each month YoY?
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - deals_created_date_month_name
    - deals_created_date_year
  exploreName: deals
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - deals_total_amount
  sorts:
    - descending: true
      fieldId: deals_created_date_year
  tableCalculations: []
name: YoY Revenue vs. Target
pivotConfig:
  columns:
    - deals_created_date_year
slug: yoy-revenue
spaceSlug: shared/demo-space/sales-marketing
tableConfig:
  columnOrder:
    - deals_created_date_month_name
    - deals_created_date_year
    - deals_total_amount
tableName: deals
verification: null
version: 1
